### ISSUE TITLE
Listings with nil categories don't show up in All Listings

### ISSUE THREAD

**Issue by ew2664** [ew2664/rentdash#1]
All Listings filters based on the selected categories, so the listings that have "nil" categories are filtered out even when all categories are selected because they don't belong to any of them.

I think we should still allow item_category to be nil because not every listing needs to be categorized. Maybe add another "Other" select option in the UI that the listings with "nil" categories are gathered under.

**Comment by nathannguyen58** [comment]
Solved by creating a new item category option called other.
