### ISSUE TITLE
Form validation and error messages

### ISSUE THREAD

**Issue by ew2664** [ew2664/rentdash#2]
When user inputs invalid data into a form (e.g., submitting a blank new listing form) and field-specific errors are returned, currently the errors are just printed at the top of the page. These should be displayed in a nicer way, ideally with each error linked to each field.

**Comment by nathannguyen58** [comment]
Resolved for every form except for "edit rental". We needed to render the action for each form page that might have errors. However, when doing this for the rentals edit page, we ran into an error since it's no longer able to access the listing variable... still looking into this.

**Comment by catw101** [comment]
Fixed.
