### ISSUE TITLE
Invalid form loses previous input

### ISSUE THREAD

**Issue by ew2664** [ew2664/rentdash#3]
When a user submits an invalid form (e.g. when creating a new listing), even if one field is wrong, the whole form gets cleared and they have to start over, which is a bit annoying. Ideally the form would save the previous inputs in flash and load it back in when the page is refreshed.

**Comment by nathannguyen58** [comment]
I resolved this error by rendering the respective rails actions rather than redirecting to the paths. However, the flashed error now seems to be unrecognizable.

**Comment by catw101** [comment]
Fixed the flashed error.
